# Generated by Django 5.0.4 on 2024-11-14 06:55

import django.db.models.deletion
import django.utils.timezone
import flowchart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowchartEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=flowchart.models.upload_to_author)),
            ],
        ),
        migrations.CreateModel(
            name='FlowchartNest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=flowchart.models.upload_to_author)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dir_name', models.CharField(default='default_flowchart_directory', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Flowchart',
        ),
        migrations.AddField(
            model_name='flowchartentry',
            name='flowchart_nest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowchart_files', to='flowchart.flowchartnest'),
        ),
    ]
