# Generated by Django 5.0.4 on 2024-11-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadMate', '0002_filenest_dir_name_filenest_is_directory_fileentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filenest',
            name='file',
        ),
        migrations.RemoveField(
            model_name='filenest',
            name='is_directory',
        ),
    ]
