# Generated by Django 5.0.4 on 2024-11-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadMate', '0003_remove_filenest_file_remove_filenest_is_directory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filenest',
            name='dir_name',
            field=models.CharField(default='default_directory', max_length=255),
        ),
    ]
