# Generated by Django 5.0.4 on 2024-11-28 06:46

import uploadMate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadMate', '0006_alter_filenest_dir_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileentry',
            name='file',
            field=models.FileField(max_length=5000, upload_to=uploadMate.models.upload_to_author),
        ),
    ]
