# Generated by Django 5.0.4 on 2024-11-18 11:50

import django.db.models.deletion
import django.utils.timezone
import summaryGen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaryGen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=summaryGen.models.upload_to_author)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryNest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=summaryGen.models.upload_to_author)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dir_name', models.CharField(default='default_summary_directory', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SummaryDoc',
        ),
        migrations.AddField(
            model_name='summaryentry',
            name='sequence_diagram_nest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_files', to='summaryGen.summarynest'),
        ),
    ]
