# Generated by Django 5.0.4 on 2024-11-18 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaryGen', '0002_summaryentry_summarynest_delete_summarydoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryentry',
            name='sequence_diagram_nest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_diagram_files', to='summaryGen.summarynest'),
        ),
    ]
